### PR TITLE
Added Canonical HTTPS support

### PR DESCRIPTION
**Pull request by zengoma**
Hey, A small enhancement: take it or leave it. I've given users the ability to point all pages to the https:// canonical version of the page which further enhances google rankings for sites with a valid ssl certificate.

As per google article: [Prefer https over http](https://support.google.com/webmasters/answer/139066?hl=en#https)

### CODE REVIEW

**Comment by imsamthomas** [comment]
Thanks for the great contribution.
Hope you can do like this frequently ;)

We are processing merge the pull request now.

Regards,
Sam

**Comment by zengoma** [comment]
Only a pleasure Sam. Thanks for doing most of the dirty work. I'm using your SEO module on my website, https://afrozania.com. I have developed several modules myself including the mega menu's, the flickity product carousel and the alphabetical product index pages that you will notice on the website(among others).  I've found the free modules on Mageplaza very helpful so to show my thanks please feel free to request any of my custom modules, you are welcome to distribute them on Mageplaza.


I'm quite busy at the moment but when I get a chance I have several more contributions I'd like to make to the SEO module. In the meantime, there is an improvement that could be made. I noticed two product rich snippets appearing per product view page. Your implementation (bottom product) as well as the magento implementation(top product). You will also see that magento has incorrectly placed the currency symbol in the price snippet tag. I think placing the snippets at html tag level as magento has done is wise. I say this because I have chosen to hide the sku from the customer by removing it from the layout. This automatically removes it from the magento's rich snippet but not yours. Do you think that having the same product snippet in duplicate will cause issues? If so it will have to be rectified. I'll look into this when I get a chance but let me know your thoughts.


 

Kind regards
Lance
---- On Thu, 18 Aug 2016 16:55:02 +0200 Sam &lt;notifications@github.com&gt; wrote ---- 

Thanks for the great contribution.
 Hope you can do like this frequently ;)
 We are processing merge the pull request now.
 Regards,
 Sam

**Comment by imsamthomas** [comment]
Hi Lance,

Thank you very much.
Yes, I saw Magento default has HTML snippet in Luma theme.
But if may effect if changing theme. That why we implement json data format. So we can add anywhere on the page without conflict with theme, custom design.

At this moment, we have no idea to remove default snippet avoid duplicate issue.

Any suggestion/contribute on this?

Best Regards,
Sam

**Comment by zengoma** [comment]
Hi Sam

You make a good point, in my case I extended the Luma theme but it is impossible to override potential snippets in other themes that may or may not use structured data. The only way I can think of addressing this would be to create an option in the admin section that allows the user to disable rich snippets for products? They can either then redesign their theme and remove the theme snippets OR disable the mageplaza snippets and keep their own custom theme snippets. What do you think? I can create a pull request for this at some stage this week if I get a chance... let me know what you think. 


Totally unrelated, I have been struggling to change the robots meta tag for individual products using the design layout xml update section of the product. Magento has acknowledged that this is an issue and they will fix it at some stage: https://community.magento.com/t5/Magento-2-Feature-Requests-and/how-to-change-the-robots-meta-tag-only-in-a-static-page/idi-p/46100. So I dont know if it's worth creating an extra mageplaza seo section for individual products that will allow a user to override the default robots meta tag? If I have time I'll propose the feature via pull request.


Thanks! Ciao!




---- On Thu, 08 Sep 2016 05:28:56 +0200 Sam &lt;notifications@github.com&gt; wrote ---- 

Hi Lance,
 Thank you very much.
 Yes, I saw Magento default has HTML snippet in Luma theme.
 But if may effect if changing theme. That why we implement json data format. So we can add anywhere on the page without conflict with theme, custom design.
 At this moment, we have no idea to remove default snippet avoid duplicate issue.
 Any suggestion/contribute on this?
 Best Regards,
 Sam

**Pull request merged**
